title = "TOML Example"

[[items]]
id = "123"
name = "Item 1"
[[items.actions]]
id = "123456"
name = "Item 1-1"
[[items.actions]]
id = "456789"
name = "Item 1-2"

[[items]]
id = "456"
name = "Item 2"

[[items.actions]]
id = "123456"
name = "Item 2-1"
[[items.actions]]
id = "456789"
name = "Item 2-2"


[[items]]
id = "789"
name = "Item 3"

[[items.actions]]
id = "123456"
name = "Item 3-1"
[[items.actions]]
id = "456789"
name = "Item 3-2"
